### PR TITLE
Don't use hardcoded ssb-chess-db version

### PR DESCRIPTION
**Pull request by arj03**
npm ls ssb-chess-db gives me 2 versions. 1.0.1 in main and 1.0.0 in ssb-chess. This should solve that.

### CODE REVIEW

**Comment by Happy0** [comment]
Actually, I think we can just remove this line since it's patchbay that deals with installing the plugin for scuttlebot, etc.

You can change this pull request to remove that dependency, if you like? Otherwise, I can do it :P

By the way, I hope I can solve the issue you're having with your development stand-alone version of scuttlebot. I tried at the weekend, but I messed up my environment and have stopped looking into it for now :P

**Comment by arj03** [comment]
Done :)

**Comment by arj03** [comment]
I tried your latest version. Still doesn't load, wasn't sure if it was related to this or not, but it looked wrong :)

**Comment by Happy0** [comment]
Awesome, thanks :).

I'll PM you on scuttlebutt and we can try and work out what your issue is. I wonder if your environment is broken in a similar way to mines was at the weekend after trying to install the plugin for my standalone sbot.

**Pull request merged**
